name: number-converter-ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit tests
      run: ./gradlew test

    - name: Functional tests
      run: ./gradlew functionalTest

    - name: Test all roman conversions
      run: ./gradlew convertAllRomanNumbersTest --info

    - name: Roman -> Arabic
      run: ./gradlew romanToArabic

    - name: Arabic -> Roman
      run: ./gradlew arabicToRoman

    - name: Test with diverse inputs
      run: ./gradlew miscConversions
